#!/bin/bash

#Kas arv on algarv või mitte. Täiendus: Kas esimesed 20 arvu on algarvud või mitte?

for (( arv=1; arv<21; arv++ ))

do

summa=0

if [ $arv -eq 0 -o $arv -eq 1 ];

then
	echo "$arv ei ole algarv"

else

	jagaja=2
	jaak=$(($arv % $jagaja))
	while [ $jaak -ne 0 ]

	do
		jagaja=$(($jagaja + 1))
		jaak=$(($arv % $jagaja))
	done

if [ $arv -eq $jagaja ];

then

	echo "$arv on algarv"

else
	echo "$arv ei ole algarv"

	fi

fi

done
