#!/bin/bash

#Sisseehitatud tsükklid



for (( i = 1 ; i <= 5; i++ ))   ###Outer for loop###

do

	for (( j = 1 ; j <= 5; j++)) ###Inner for loop###

	do
		echo -n ""*" "

	done

	echo "" #print a new line#

done
