#!/bin/bash

#Ludvig-Erik Lidmets, skript kujund
#Sisestatakse kujundi ridade arv ja trükib kujundi mis koosneb vastavast ridade arvust

echo "Sisestage ridade arv: "
read rida

for (( i = 1; i <= $rida; i++ ))      ### Välimine for loop - mitu rida peab printima

do


  		 for (( j = 1; j <= i; j++ )) ### Sisemine for loop - mitu tärni peab printima reale

		 do

			  echo -n "* "

    done

  echo "" #### Prindib tühja rea

done | tac
