#!/bin/bash

#Ludvig-Erik Lidmets, skript menu
#Väljastab kasutajale menüü, küsib valikut ning  väljastab söögi kirjelduse

osch=0

echo "1) Liha ja kartulid"
echo "2) Kala ja krõpsud"
echo "3) supp ja salat"

echo -ne "Tee oma valik (1-3): "
read osch

if [ $osch -eq 1 ] ; #Esimene if lause - kui read on 1, siis echotakse see
	then
		echo "Väga maitsev, aga jälgi oma tervist!"
		echo "Head isu!"

else

	if [ $osch -eq 2 ] ; #If lause if lause sees - kui read on 2, siis echotakse see

		then

			echo "Brititoit on maitsev!"
			echo "Head isu!"

else #Siia pole vaja -eq 3, kuna see on ainus variant mis on alles. - kui read on 3 siis echotakse see

	echo "Nii tervislik ja igav..."
	echo "Head isu!"

	fi

fi
