#!/bin/bash

#Küsib arvu ja väljastab kas on paaris või paaritu arv

echo -n  "Sisesta suvaline täisarv: "
read arv

#Jäägi arvutamine /Jagame kahega

jaak=$(($arv % 2))

#4%2 on 0 siis arv on paaris
#5%2 on 1 siis arv on paaritu

if [ $jaak -eq 0 ]

then
	echo "$arv on paaris"
else
	echo "$arv on paaritu"
fi
