#!/bin/bash

#Bussiekskursiooni abistaja, lisab juurde bussi kui reisijad ei mahu bussi.

echo "Mitu kohta on bussis? "
read koht
echo "Mitu reisjat on grupis? "
read arv

bussid=$((arv/koht))

ylejaanud=$((arv % koht))

if test $ylejaanud -gt 0
then
	bussid=$(($bussid + 1))
fi

echo "Kokku on vaja $bussid täis bussi"
